### ISSUE TITLE
nullable types (nullable vs non-nullable operands)

### ISSUE THREAD

**Issue by emiliovmq** [dadhi/FastExpressionCompiler#183]
Hi, while my first snippet of code works like a charm using the Compile method, it is failing when using FEC.   I've noticed this malfunction only occurs when one of the operands is decimal or nullable decimal (decimal?). Any idea???

```
static void TestNullableByteVsDecimal()
        {
            ParameterExpression parameterExpression = Expression.Parameter(typeof(GeneralContainer));
            MemberExpression left = Expression.Property(parameterExpression, nameof(GeneralContainer.NullableByte));
            MemberExpression right = Expression.Property(parameterExpression, nameof(GeneralContainer.Decimal));
            BinaryExpression body = Expression.Equal(Expression.Convert(left, typeof(decimal?)), Expression.Convert(right, typeof(decimal?)));
            ParameterExpression[] obj = new ParameterExpression[1];
            obj[0] = parameterExpression;
            Func<GeneralContainer, bool> fctn = Expression.Lambda<Func<GeneralContainer, bool>>(body, obj).Compile();

            var result = fctn(new GeneralContainer() { Decimal = 1 });
            Console.WriteLine(result);
            result = fctn(new GeneralContainer() { NullableByte = 1, Decimal = 1 });
            Console.WriteLine(result);
            result = fctn(new GeneralContainer() { NullableByte = null, Decimal = 1 });
            Console.WriteLine(result);
            result = fctn(new GeneralContainer() { NullableByte = null });
            Console.WriteLine(result);
        }

        static void TestNullableByteVsDecimalFEC()
        {
            ParameterExpression parameterExpression = Expression.Parameter(typeof(GeneralContainer));
            MemberExpression left = Expression.Property(parameterExpression, nameof(GeneralContainer.NullableByte));
            MemberExpression right = Expression.Property(parameterExpression, nameof(GeneralContainer.Decimal));
            BinaryExpression body = Expression.Equal(Expression.Convert(left, typeof(decimal?)), Expression.Convert(right, typeof(decimal?)));
            ParameterExpression[] obj = new ParameterExpression[1];
            obj[0] = parameterExpression;
            Func<GeneralContainer, bool> fctn = Expression.Lambda<Func<GeneralContainer, bool>>(body, obj).CompileFast();

            var result = fctn(new GeneralContainer() { Decimal = 1 });  // Exception: 
            Console.WriteLine(result);
            result = fctn(new GeneralContainer() { NullableByte = 1, Decimal = 1 });
            Console.WriteLine(result);
            result = fctn(new GeneralContainer() { NullableByte = null, Decimal = 1 });
            Console.WriteLine(result);
            result = fctn(new GeneralContainer() { NullableByte = null });
            Console.WriteLine(result);
        }

```
the exception detail:
System.InvalidOperationException
  HResult=0x80131509
  Message=Nullable object must have a value.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_NoValue()
   at OneSpaWorld.Rql.LinQ.Research.Program.TestNullableByteVsDecimalFEC() in C:\Work\Src\dotnet\workspace\repos\Olympus\OneSpaWorld.Rql\OneSpaWorld.Rql.LinQ.Research\Program.cs:line 209
   at OneSpaWorld.Rql.LinQ.Research.Program.Main(String[] args) in C:\Work\Src\dotnet\workspace\repos\Olympus\OneSpaWorld.Rql\OneSpaWorld.Rql.LinQ.Research\Program.cs:line 223

**Comment by dadhi** [comment]
Yeah, I love decimal and nullables :(

Please, add the failing tests into `...IssuesTests` project and submit the PR. Mark tests with `[Ignore("fixme")]` attribute for CI build to pass. 
Then someone (including me or you) will fix it.

**Comment by dadhi** [comment]
@emiliovmq Linking your PR here: #184
