### ISSUE TITLE
Expression.New does not work with struct

### ISSUE THREAD

**Issue by Dolfik1** [dadhi/FastExpressionCompiler#231]
Repo code:
```csharp
struct Example { }

[Fact]
public void Test()
{
  Expression.New(typeof(Example));
}
```

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no matching element
  Source=System.Linq
  StackTrace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FastExpressionCompiler.LightExpression.Expression.New(Type type) in D:\Dev\FastExpressionCompiler\src\FastExpressionCompiler.LightExpression\Expression.cs:line 83
```

**Comment by dadhi** [comment]
Thanks for the test, will check.
