### ISSUE TITLE
NRE in IndexExpression.get_ArgumentCount

### ISSUE THREAD

**Issue by GeroL** [dadhi/FastExpressionCompiler#319]
Stack:

```
System.NullReferenceException: Object reference not set to an instance of an object.
         at FastExpressionCompiler.LightExpression.IndexExpression.get_ArgumentCount() in /_/src/FastExpressionCompiler.LightExpression/Expression.cs:line 3132
        at FastExpressionCompiler.LightExpression.ExpressionCompiler.TryCollectBoundConstants(ClosureInfo& closure, Expression expr, IParameterProvider paramExprs, Boolean isNestedLambda, ClosureInfo& rootClosure, CompilerFlags flags) in /_/src/FastExpressionCompiler/FastExpressionCompiler.cs:line 1382
         at FastExpressionCompiler.LightExpression.ExpressionCompiler.TryCollectBoundConstants(ClosureInfo& closure, Expression expr, IParameterProvider paramExprs, Boolean isNestedLambda, ClosureInfo& rootClosure, CompilerFlags flags) in /_/src/FastExpressionCompiler/FastExpressionCompiler.cs:line 1360
         at FastExpressionCompiler.LightExpression.ExpressionCompiler.TryCompileBoundToFirstClosureParam(Type delegateType, Expression bodyExpr, IParameterProvider paramExprs, Type[] closurePlusParamTypes, Type returnType, CompilerFlags flags) in /_/src/FastExpressionCompiler/FastExpressionCompiler.cs:line 467
         at FastExpressionCompiler.LightExpression.ExpressionCompiler.CompileFast[T1,T2,R](Expression`1 lambdaExpr, Boolean ifFastFailedReturnNull, CompilerFlags flags) in /_/src/FastExpressionCompiler/FastExpressionCompiler.cs:line 220
```

I think its because of this code:
```
public class ManyArgumentsIndexExpression : IndexExpression
    {
        public sealed override IReadOnlyList<Expression> Arguments { get; }
        internal ManyArgumentsIndexExpression(Expression @object, IReadOnlyList<Expression> arguments) : base(@object) =>
            Arguments = arguments;
    }
```

It does not check the parameter and does not initialize the Arguments property.

Please consider splitting that file as debugging is very difficult. The line numbers are always different from the stacktrace.

**Comment by GeroL** [comment]
Compiles and works with System.Linq.Expressions.
Line for CSharpPrinter: https://github.com/dadhi/FastExpressionCompiler/blob/6c5d555cf33c679c994f0fbaeef38f5a20acbc7e/src/FastExpressionCompiler/FastExpressionCompiler.cs#L6441
Line for Compiler:
https://github.com/dadhi/FastExpressionCompiler/blob/6c5d555cf33c679c994f0fbaeef38f5a20acbc7e/src/FastExpressionCompiler/FastExpressionCompiler.cs#L1385

**Comment by dadhi** [comment]
@GeroL What is the expression you are using that compiles and works with `System.Linq.Expressions`?

**Comment by dadhi** [comment]
@GeroL I have added as small fix for NRE.
