### ISSUE TITLE
Cannot run unit Tests with VS 2017.6 NUnitTest Adapter 3.9

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dadhi/FastExpressionCompiler#61]
Tests are visible but do not run

![image](https://user-images.githubusercontent.com/757125/37239849-2e3cccb2-2453-11e8-8fb2-0637960ea89b.png)

Tried both bitnesses:

![image](https://user-images.githubusercontent.com/757125/37239865-59710a10-2453-11e8-9aff-a53bceb89132.png)

Seems this root cause:
```
[10-Mar-18 11:07:51 Informational] Executing all tests in type 'FastExpressionCompiler.IssueTests.Issue55_CompileFast_crash_with_ref_parameter'
[10-Mar-18 11:07:51 Informational] ------ Run test started ------
[10-Mar-18 11:08:51 Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '1.1.2'.

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
[10-Mar-18 11:08:51 Informational] ========== Run test finished: 0 run (0:01:00.0271437) ==========
```

Could we upgrade tests and only tests to latest .NET Core? Or at least starting from 2.0 as 1.1 is to way old and useless.

**Comment by dadhi** [comment]
Currently netcore 1.1 is required to run tests on MacOS CI. Until it upgraded there, please don't remove the target completely.

But you can remove the netcore 1.1 target temporarely when developing, no problem.
