### ISSUE TITLE
Benchmarks run from VS Code on Windows 10

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dadhi/FastExpressionCompiler#80]
On latest VS latest .NET Core lastest Windows 10 I got `dotnet build` fine and `dotnet test`  almost fine.

IssueTests and UnitTests run well, but Benchmarks failed to run. See error in log by `Benchmarks` word:

```
No test is available in E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.Benchmarks\bin\Debug\netcoreapp2.0\FastExpressionCompiler.Benchmarks.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.0-preview1-26216-03 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

Test Run Aborted.
````

Whole log is here:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS E:\dzmitry\shared-src\FastExpressionCompiler> dotnet build
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.UnitTests\FastExpressionCompiler.UnitTests.csproj...
  Restoring packages for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\FastExpressionCompiler.IssueTests.csproj...
  Restoring packages for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.Benchmarks\FastExpressionCompiler.Benchmarks.csproj...
  Restore completed in 67.86 ms for E:\dzmitry\shared-src\FastExpressionCompiler\src\FastExpressionCompiler\FastExpressionCompiler.csproj.
  Restore completed in 716.96 ms for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\FastExpressionCompiler.IssueTests.csproj.
  Restore completed in 816.23 ms for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.UnitTests\FastExpressionCompiler.UnitTests.csproj.
  Restore completed in 1.05 sec for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.Benchmarks\FastExpressionCompiler.Benchmarks.csproj.
  FastExpressionCompiler -> E:\dzmitry\shared-src\FastExpressionCompiler\src\FastExpressionCompiler\bin\Debug\net45\FastExpressionCompiler.dll
  FastExpressionCompiler -> E:\dzmitry\shared-src\FastExpressionCompiler\src\FastExpressionCompiler\bin\Debug\netstandard1.3\FastExpressionCompiler.dll
Issue55_CompileFast_crash_with_ref_parameter.cs(281,17): warning CS0219: The variable 'x' is assigned but its value is never used [E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\FastExpressionCompiler.IssueTests.csproj]
Issue55_CompileFast_crash_with_ref_parameter.cs(18,48): warning CS0649: Field 'Issue55_CompileFast_crash_with_ref_parameter.StructWithIntField.IntField' is never assigned to, and will always have its default value 0 [E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\FastExpressionCompiler.IssueTests.csproj]
  FastExpressionCompiler.UnitTests -> E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.UnitTests\bin\Debug\net46\FastExpressionCompiler.UnitTests.dll
  FastExpressionCompiler.IssueTests -> E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\bin\Debug\net46\FastExpressionCompiler.IssueTests.dll
Issue55_CompileFast_crash_with_ref_parameter.cs(281,17): warning CS0219: The variable 'x' is assigned but its value is never used [E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\FastExpressionCompiler.IssueTests.csproj]
Issue55_CompileFast_crash_with_ref_parameter.cs(18,48): warning CS0649: Field 'Issue55_CompileFast_crash_with_ref_parameter.StructWithIntField.IntField' is never assigned to, and will always have its default value 0 [E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\FastExpressionCompiler.IssueTests.csproj]
  FastExpressionCompiler.UnitTests -> E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.UnitTests\bin\Debug\netcoreapp2.0\FastExpressionCompiler.UnitTests.dll
  FastExpressionCompiler.UnitTests -> E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.UnitTests\bin\Debug\netcoreapp1.1\FastExpressionCompiler.UnitTests.dll
  FastExpressionCompiler.IssueTests -> E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\bin\Debug\netcoreapp2.0\FastExpressionCompiler.IssueTests.dll
  FastExpressionCompiler.Benchmarks -> E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.Benchmarks\bin\Debug\net462\FastExpressionCompiler.Benchmarks.exe
  FastExpressionCompiler.Benchmarks -> E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.Benchmarks\bin\Debug\netcoreapp2.0\FastExpressionCompiler.Benchmarks.dll

Build succeeded.

Issue55_CompileFast_crash_with_ref_parameter.cs(281,17): warning CS0219: The variable 'x' is assigned but its value is never used [E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\FastExpressionCompiler.IssueTests.csproj]
Issue55_CompileFast_crash_with_ref_parameter.cs(18,48): warning CS0649: Field 'Issue55_CompileFast_crash_with_ref_parameter.StructWithIntField.IntField' is never assigned to, and will always have its default value 0 [E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\FastExpressionCompiler.IssueTests.csproj]
Issue55_CompileFast_crash_with_ref_parameter.cs(281,17): warning CS0219: The variable 'x' is assigned but its value is never used [E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\FastExpressionCompiler.IssueTests.csproj]
Issue55_CompileFast_crash_with_ref_parameter.cs(18,48): warning CS0649: Field 'Issue55_CompileFast_crash_with_ref_parameter.StructWithIntField.IntField' is never assigned to, and will always have its default value 0 [E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\FastExpressionCompiler.IssueTests.csproj]
    4 Warning(s)
    0 Error(s)

Time Elapsed 00:00:10.54
PS E:\dzmitry\shared-src\FastExpressionCompiler> dotnet test
Build started, please wait...
Build started, please wait...
Build started, please wait...
Build started, please wait...
Build completed.

Test run for E:\dzmitry\shared-src\FastExpressionCompiler\src\FastExpressionCompiler\bin\Debug\net45\FastExpressionCompiler.dll(.NETFramework,Version=v4.5)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in E:\dzmitry\shared-src\FastExpressionCompiler\src\FastExpressionCompiler\bin\Debug\net45\FastExpressionCompiler.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Test run for E:\dzmitry\shared-src\FastExpressionCompiler\src\FastExpressionCompiler\bin\Debug\netstandard1.3\FastExpressionCompiler.dll(.NETStandard,Version=v1.3)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Build completed.

Build completed.

Test run for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.UnitTests\bin\Debug\net46\FastExpressionCompiler.UnitTests.dll(.NETFramework,Version=v4.6)
Test run for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\bin\Debug\net46\FastExpressionCompiler.IssueTests.dll(.NETFramework,Version=v4.6)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
System.IO.FileNotFoundException: Unable to find tests for E:\dzmitry\shared-src\FastExpressionCompiler\src\FastExpressionCompiler\bin\Debug\netstandard1.3\FastExpressionCompiler.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate. Rerun with /diag option to diagnose further.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
Starting test execution, please wait...

Test Run Aborted.
Failed   GenericRefFromConstant
Error Message:
 System.InvalidProgramException : Common Language Runtime detected an invalid program.
Stack Trace:
   at (Byte& )
   at FastExpressionCompiler.IssueTests.Issue55_CompileFast_crash_with_ref_parameter.GenericRefFromConstant() in E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\Issue55_CompileFast_crash_with_ref_parameter.cs:line 87
Failed   RefFromConstant
Error Message:
 System.InvalidProgramException : Common Language Runtime detected an invalid program.
Stack Trace:
   at (Int32& )
   at FastExpressionCompiler.IssueTests.Issue55_CompileFast_crash_with_ref_parameter.RefFromConstant() in E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\Issue55_CompileFast_crash_with_ref_parameter.cs:line 60
Failed   RefFromLargeConstant
Error Message:
 System.InvalidProgramException : Common Language Runtime detected an invalid program.
Stack Trace:
   at (Int32& )
   at FastExpressionCompiler.IssueTests.Issue55_CompileFast_crash_with_ref_parameter.RefFromLargeConstant() in E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\Issue55_CompileFast_crash_with_ref_parameter.cs:line 250
Failed   RefSetFromParameter
Error Message:
 System.InvalidProgramException : Common Language Runtime detected an invalid program.
Stack Trace:
   at (Int32& , Int32 )
   at FastExpressionCompiler.IssueTests.Issue55_CompileFast_crash_with_ref_parameter.RefSetFromParameter() in E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\Issue55_CompileFast_crash_with_ref_parameter.cs:line 305

Total tests: 36. Passed: 32. Failed: 4. Skipped: 0.
Test Run Failed.
Test execution time: 1.7718 Seconds
Test run for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.IssueTests\bin\Debug\netcoreapp2.0\FastExpressionCompiler.IssueTests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Build completed.

Test run for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.Benchmarks\bin\Debug\net462\FastExpressionCompiler.Benchmarks.exe(.NETFramework,Version=v4.6.2)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 190. Passed: 190. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.7293 Seconds
Test run for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.UnitTests\bin\Debug\netcoreapp1.1\FastExpressionCompiler.UnitTests.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.Benchmarks\bin\Debug\net462\FastExpressionCompiler.Benchmarks.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Test run for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.Benchmarks\bin\Debug\netcoreapp2.0\FastExpressionCompiler.Benchmarks.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   GenericRefFromConstant
Error Message:
 System.InvalidProgramException : Common Language Runtime detected an invalid program.
Stack Trace:
   at (Byte& )
   at FastExpressionCompiler.IssueTests.Issue55_CompileFast_crash_with_ref_parameter.GenericRefFromConstant()
Failed   RefFromConstant
Error Message:
 System.InvalidProgramException : Common Language Runtime detected an invalid program.
Stack Trace:
   at (Int32& )
   at FastExpressionCompiler.IssueTests.Issue55_CompileFast_crash_with_ref_parameter.RefFromConstant()
Failed   RefFromLargeConstant
Error Message:
 System.InvalidProgramException : Common Language Runtime detected an invalid program.
Stack Trace:
   at (Int32& )
   at FastExpressionCompiler.IssueTests.Issue55_CompileFast_crash_with_ref_parameter.RefFromLargeConstant()
Failed   RefSetFromParameter
Error Message:
 System.InvalidProgramException : Common Language Runtime detected an invalid program.
Stack Trace:
   at (Int32& , Int32 )
   at FastExpressionCompiler.IssueTests.Issue55_CompileFast_crash_with_ref_parameter.RefSetFromParameter()

Total tests: 36. Passed: 32. Failed: 4. Skipped: 0.
Test Run Failed.
Test execution time: 2.4020 Seconds
No test is available in E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.Benchmarks\bin\Debug\netcoreapp2.0\FastExpressionCompiler.Benchmarks.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.0-preview1-26216-03 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

Test Run Aborted.
Test run for E:\dzmitry\shared-src\FastExpressionCompiler\test\FastExpressionCompiler.UnitTests\bin\Debug\netcoreapp2.0\FastExpressionCompiler.UnitTests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 190. Passed: 190. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.2691 Seconds
PS E:\dzmitry\shared-src\FastExpressionCompiler> dotnet --version
2.1.302
PS E:\dzmitry\shared-src\FastExpressionCompiler>
````

**Comment by dadhi** [comment]
The projects are converted to SDK based style. So I consider it closed.
